    - name: update and upgrade apt packages
      apt:
        state: present
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      when: ansible_os_family == 'Debian'
    - name: install misc packages
      apt:
        state: present
        pkg:
          - neofetch
          - build-essential
          - cmake
          - vim-nox
          - python3-dev
          - mono-complete
          - linux-headers-{{ ansible_kernel }}
          - git
          - curl
          - wget
          - jq
          - xclip
          - apt-transport-https
          - zsh
          - unzip
          - htop
          - python3-pip
          - ca-certificates
          - lsb-release
          - tmux
          - libarchive-tools
          - ruby-dev
          - plocate
          - tree
    - name: Create some directories
      become_user: "{{ user_name }}"
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "/home/{{ user_name }}/Downloads"
        - "/home/{{ user_name }}/Downloads/tools"
        - "/home/{{ user_name }}/Downloads/deb"
        - "/home/{{ user_name }}/.config"

    - name: Copy font
      ansible.builtin.copy:
        src: "MesloLGSNF.ttf"
        dest: "/usr/local/share/fonts/MesloLGSNF.ttf"

    - name: Update font cache
      ansible.builtin.shell:
        cmd: "fc-cache -f -v"

    - name: Add zsh completions
      become_user: "{{ user_name }}"
      git:
        repo: "https://github.com/zsh-users/zsh-completions"
        dest: "/home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-completions"
        clone: true
        update: true

    - name: Change default shell to zsh
      user:
        name: "{{ user_name }}"
        shell: /bin/zsh

    - name: Change default shell to zsh
      user:
        name: "{{ user_name }}"
        shell: /bin/zsh

    - name: Clone Powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/{{ user_name }}/.oh-my-zsh/custom/themes/powerlevel10k"
      become_user: "{{ user_name }}"

    - name: Set git config values
      git_config:
        scope: global
        name: user.name
        value: "{{ git_user_name }}"
      become_user: "{{ user_name }}"

    - name: Set git config values
      git_config:
        scope: global
        name: user.email
        value: "{{ git_user_email }}"
      become_user: "{{ user_name }}"

    - name: Set default Git editor
      git_config:
        scope: global
        name: core.editor
        value: vim
      become_user: "{{ user_name }}"
