# this is to install a laptop
# todo
# - az cli
# ln -s /etc/bash_completion.d/azure-cli ~/.oh-my-zsh/custom/az.zsh
# - vim
# - oh my zsh
# - autocomplete
# - kubectx
# - powerlevel10k
# vim ~/.p10k.zsh
# install zsh-completions
# git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions
# before source zsh:   fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
# - pcloud
# - obsidian
# - cherrytree
# - keybase
# https://flatpak.org/setup/Ubuntu
# https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_module.html
# https://odolbeau.fr/blog/how-to-install-your-laptop-with-ansible.html
# vagrant and virtualbox
# vagrant plugin install winrm
# vagrant plugin install winrm-fs
# vagrant plugin install winrm-elevated
# vagrant plugin install vagrant-disksize
# touch ~/.ssh/config
# Host ssh.dev.azure.com
#    User git
#    PubkeyAcceptedAlgorithms +ssh-rsa
#    HostkeyAlgorithms +ssh-rsa
#
# pip3 install ansible-lint
# ansible-galaxy install gantsign.oh-my-zsh
# gogh and bim 
# oh my zsh 


- hosts: localhost
  become: true
  gather_facts: True
  vars:
    vscode_url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    terraform_version: 1.1.8
    user_name: jacqueline
    repo_key_url: https://packages.microsoft.com/keys/microsoft.asc
    github_repo_key_url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    nodejs_version: 16.x
    distro: jammy
    fallback_distro: impish
  tasks:
  - name: update and upgrade apt packages
    apt:
      state: present
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
    when: ansible_os_family == 'Debian'
  - name: install misc packages
    apt:
      state: present
      pkg:
      - neofetch
      - build-essential
      - cmake
      - vim-nox
      - python3-dev
      - mono-complete
      - linux-headers-{{ ansible_kernel }}
      - git
      - curl
      - wget
      - jq
      - xclip
      - apt-transport-https
      - zsh
      - unzip
      - htop
      - python3-pip
      - ca-certificates
      - lsb-release
      - hugo
      - gnome-tweaks
      - tmux
      - vagrant
      - virtualbox-7.0
      - libarchive-tools
      - ruby-dev
      - flatpak
      - gnome-tweaks

  - name: Make dir for vim pathogen
    become_user: "{{ user_name }}"
    ansible.builtin.shell:
      cmd: "mkdir -p /home/{{ user_name }}/.vim/autoload /home/{{ user_name}}/.vim/bundle"

  - name: Install vim pathogen
    become_user: "{{ user_name }}"
    ansible.builtin.shell:
      cmd: "curl -LSso /home/{{ user_name }}/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim"

  - name: Add vim plugins
    become_user: "{{ user_name }}"
    git:
      repo: "{{ item.repo }}"
      dest: "/home/{{ user_name }}/.vim/bundle/{{ item.dest }}"
      clone: true
      update: true
    loop:
      - { repo: 'https://github.com/scrooloose/nerdtree.git', dest: 'nerdtree' }
      - { repo: 'https://github.com/Valloric/MatchTagAlways.git', dest: 'MatchTagAlways' }
      - { repo: 'https://github.com/ctrlpvim/ctrlp.vim.git', dest: 'ctrlp.vim' }
      - { repo: 'https://github.com/vim-airline/vim-airline.git', dest: 'vim-airline' }
      - { repo: 'https://github.com/vim-airline/vim-airline-themes.git', dest: 'vim-airline-themes' }
      - { repo: 'https://github.com/lukaszb/vim-web-indent.git', dest: 'vim-web-indent' }
      - { repo: 'https://github.com/hashivim/vim-vagrant.git', dest: 'vim-vagrant' }
      - { repo: 'https://github.com/altercation/vim-colors-solarized.git', dest: 'vim-colors-solarized' }
      - { repo: 'https://github.com/w0rp/ale.git', dest: 'ale' }
      - { repo: 'https://github.com/Yggdroot/indentLine.git', dest: 'indentLine' }
      - { repo: 'https://github.com/ntpeters/vim-better-whitespace.git', dest: 'vim-better-whitespace' }
      - { repo: 'https://github.com/tpope/vim-surround.git', dest: 'vim-surround' }
      - { repo: 'https://github.com/mattn/emmet-vim.git', dest: 'emmet-vim' }
      - { repo: 'https://github.com/nathanaelkane/vim-indent-guides', dest: 'vim-indent-guides' }
      - { repo: 'https://github.com/pearofducks/ansible-vim', dest: 'ansible-vim' }

  - name: Create vim colors dir
    become_user: "{{ user_name }}"
    file:
      path: "/home/{{ user_name }}/.vim/colors"
      state: directory

  - name: Download colorschemes
    become_user: "{{ user_name }}"
    get_url:
      url: "{{ item.url }}"
      dest: "/home/{{ user_name }}/.vim/colors/{{ item.file }}"
    loop:
      - { url: 'https://raw.githubusercontent.com/cocopon/iceberg.vim/master/colors/iceberg.vim', file: 'iceberg.vim' }
      - { url: 'https://raw.githubusercontent.com/arcticicestudio/nord-vim/main/colors/nord.vim', file: 'nord.vim' }

  - name: Copy vimrc
    become_user: "{{ user_name }}"
    ansible.builtin.copy:
      src: "vimrc"
      dest: "/home/{{ user_name }}/.vimrc"

  - name: Copy tmux
    become_user: "{{ user_name }}"
    ansible.builtin.copy:
      src: "tmux.conf"
      dest: "/home/{{ user_name }}/.tmux.conf"


  - name: Create downloads/debs dir
    become_user: "{{ user_name }}"
    file:
      path: "/home/{{ user_name }}/Downloads/debs"
      state: directory

  - name: Download vscode
    get_url:
      url: "{{ vscode_url }}"
      dest: "/home/{{ user_name }}/Downloads/debs/vscode.deb"

  - name: Install vscode
    apt: deb="/home/{{ user_name }}/Downloads/debs/vscode.deb"
      state=present
    
  - name: download chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dest: "/home/{{ user_name }}/Downloads/debs/chrome.deb"

  - name: install chrome
    apt: deb="/home/{{ user_name }}/Downloads/debs/chrome.deb"
      state=present

  - name: enable flatpak repo
    ansible.builtin.shell:
      cmd:  "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

  - name: install multiple flatpak packages
    community.general.flatpak:
      name: "{{ item }}"
      state: present
    loop:
      - com.giuspen.cherrytree
      - md.obsidian.Obsidian
      - org.flameshot.Flameshot
      - net.xmind.XMind8
      - com.getpostman.Postman
      - io.dbeaver.DBeaverCommunity
      - com.todoist.Todoist
      - com.bitwarden.desktop
      - io.podman_desktop.PodmanDesktop
      - com.slack.Slack

  - name: download z.sh
    become_user: "{{ user_name }}"
    get_url:
      url: https://raw.githubusercontent.com/rupa/z/master/z.sh
      dest: "/home/{{ user_name }}/.config/z.sh"
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: "/home/{{ user_name }}/.config/z.sh"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0744'

  - name: Copy font
    ansible.builtin.copy:
      src: "MesloLGSNF.ttf"
      dest: "/usr/local/share/fonts/MesloLGSNF.ttf"

  - name: Update font cache
    ansible.builtin.shell:
      cmd: "fc-cache -f -v"

  - name: Check if .zshrc exists
    stat:
      path: "/home/{{ user_name }}/.zshrc"
    register: stat_zshrc

  - name: Check if .oh-my-zsh exists
    ansible.builtin.stat:
      path: "/home/{{ user_name }}/.oh-my-zsh"
    register: stat_oh_my_zsh_result

  - name: Clone oh-my-zsh
    git:
      repo: https://github.com/robbyrussell/oh-my-zsh
      dest: "/home/{{ user_name }}/.oh-my-zsh"
    when: stat_oh_my_zsh_result.stat.exists is not defined

  - name: Copy zshrc
    become_user: "{{ user_name }}"
    ansible.builtin.copy:
      src: "zshrc"
      dest: "/home/{{ user_name }}/.zshrc"
    when: stat_zshrc.stat.exists is not defined

  - name: Add zsh completions
    become_user: "{{ user_name }}"
    git:
      repo: "https://github.com/zsh-users/zsh-completions"
      dest: "/home/{{ user_name }}/.oh-my-zsh/custom/plugins/zsh-completions"
      clone: true
      update: true

  - name: Set git info
    become_user: "{{ user_name }}"
    ansible.builtin.shell:
      cmd: "git config --global user.mail 'jportier@microsoft.com' && git config --global user.name 'Jacqueline Portier'"
