- hosts: master
  become: yes
  tasks:
    - name: getting helm
      shell: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash 
      args:
        chdir: $HOME
        creates: gets_helm.txt
 
    - name: install helm clusterrolebinding
      shell: kubectl create clusterrolebinding permissive-binding --clusterrole=cluster-admin --user=admin --user=kubelet --group=system:serviceaccounts
      args:
        chdir: $HOME
        creates: cluster_rolebinding.txt
      ignore_errors: yes
    
    - name: helm init
      shell: helm init --service-account default
      args:
        chdir: $HOME
        creates: helm_init.txt
      ignore_errors: yes
   
    - name: helm install ingress
      shell: helm install stable/nginx-ingress --namespace kube-system --set controller.hostNetwork=true --set rbac.create=true --set controller.kind=DaemonSet
      args:
        chdir: $HOME
        creates: helm_install_ingress.txt
      ignore_errors: yes
   
    - name: install dashboard
      shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml
      args:
        chdir: $HOME
        creates: install_dashboard.txt
      ignore_errors: yes

    - name: create service account for dashboard
      shell: kubectl create serviceaccount cluster-admin-dashboard-sa
      args:
        chdir: $HOME
        creates: create_sa_for_dashboard.txt

    - name: create cluster role binding for dashboard
      shell: kubectl create clusterrolebinding cluster-admin-dashboard-sa --clusterrole=cluster-admin --serviceaccount=default:cluster-admin-dashboard-sa
      args:
        chdir: $HOME
        creates: creat_custer_role_dashboard.txt
      ignore_errors: yes
