# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "master" do |master_config|
    master_config.vm.box = "ubuntu/bionic64"
    
    config.vm.network "public_network"
    master_config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 2048	
      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end

  config.vm.define "worker01" do |worker01_config|
      worker01_config.vm.box = "ubuntu/bionic64"
      worker01_config.vm.provider "virtualbox" do |v|
        v.linked_clone = true
        v.memory = 2048	
        v.customize ["modifyvm", :id, "--vram", "128"]
        v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end

  config.vm.define "worker02" do |worker02_config|
    worker02_config.vm.box = "ubuntu/bionic64"
    worker02_config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.memory = 2048
      v.customize ["modifyvm", :id, "--vram", "128"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end
  config.vm.network "public_network"
 
end

